### ISSUE TITLE
can i use query to spell sql but not make real connection?

### ISSUE THREAD

**Issue by SheSnake** [tangentsoft/mysqlpp#6]
can i use query to spell sql but not make real connection?
for example:
1.
auto conn = std::unique_ptr<mysqlpp::Connection>();
conn->driver()->connect(nullptr, nullptr, 0, nullptr, nullptr, nullptr); 
auto query = conn->Query()
then use query as a stream...

**Comment by tangentsoft** [comment]
You don't have to manually dig down to the DBDriver level. Read the examples.

**Comment by SheSnake** [comment]
> You don't have to manually dig down to the DBDriver level. Read the examples.

excuse me, I find all the examples are base on the successful db connection. I hope to take use of the mysqlpp::Query to spell SQL but without make a real connection to DB. Because my project have to make connection with another lib, but it did not provide a safe way to spell SQL...

I make a serach of mysqlpp and libmysql,  if try like this
```
auto conn = std::unique_ptr<mysqlpp::Connection>(new mysqlpp::Connection());
conn->driver()->connect(nullptr, nullptr, 0, nullptr, nullptr, nullptr); 
auto query = conn->Query()
query << .... << ....;
...
...
std::string sql = query.str();
```
I can skip the connection and make the `escaped_string SQL` I want, but the `escape charset` will use `latin1` instead of `utf8` what my database was set.
Is there a better way to make a `fake db connection` and `manually set charset` of it ?

**Comment by tangentsoft** [comment]
>  the escape charset will use latin1 instead of utf8 what my database was set.

**Comment by tangentsoft** [comment]
>  the escape charset will use latin1 instead of utf8 what my database was set.

That's why you need a real connection: in MySQL, the character set can be per-database, even per-table, so correct "spelling", as you put it, varies depending on what databases and tables you're querying. To do this while disconnected is to make the MySQL C API guess.

> Is there a better way to make a fake db connection

MySQL++ doesn't have a way to swap in generic DB drivers, because it's made for use with MySQL/MariaDB.

The [libtabula project](https://github.com/tangentsoft/libtabula) is a MySQL++ successor, and part of what it's trying to accomplish is to allow swappable DBDrivers. It's currently stuck on the last step: generalizing the type system between DBMSes. If you wanted to help me solve that, then you would be able to write your own "no database" driver, with whatever behaviors you like.
